schemaVersion: "2.2.0"
metadata:
  name: cities-demo
  namespace: smichard-devspaces
  attributes:
    metadata-name-field: generateName
    metadata-name-original-value: cities_demo
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
  controller.devfile.io/devworkspace-config:
    name: devworkspace-config
    namespace: openshift-operators
  controller.devfile.io/scc: container-build
  controller.devfile.io/storage-type: per-user
  dw.metadata.annotations:
    che.eclipse.org/devfile-source: |
      url:
        location: https://github.com/smichard/cities_demo
      factory:
        params: url=https://github.com/smichard/cities_demo
projects:
  - name: cities-demo
    git:
      remotes:
        origin: https://github.com/smichard/cities_demo.git
components:
  - name: devspaces-container
    container:
      #image: quay.io/michard/developer_image:devspaces-1.0.0-20231218-203036
      image: image-registry.openshift-image-registry.svc:5000/build-environment/developer_image:1.0.0-20231224-153056
      sourceMapping: /projects
      env:
        - name: CHE_DASHBOARD_URL
          value: https://devspaces.apps.ocp.michard.cc
        - name: CHE_PLUGIN_REGISTRY_URL
          value: https://devspaces.apps.ocp.michard.cc/plugin-registry/v3
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: http://plugin-registry.openshift-operators.svc:8080/v3
        - name: CLUSTER_CONSOLE_URL
          value: https://console-openshift-console.apps.ocp.michard.cc
        - name: CLUSTER_CONSOLE_TITLE
          value: OpenShift console
        - name: OPENVSX_REGISTRY_URL
          value: 'https://open-vsx.org/'
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475   
commands:
  - id: start-kubedock
    exec:
      label: '1. Start kubedock'
      component: devspaces-container
      commandLine: kubedock server --port-forward
  - id: pull
    exec:
      label: '2. Pull Base Image'
      component: devspaces-container
      commandLine: podman pull registry.access.redhat.com/ubi8/nginx-122
  - id: build
    exec:
      label: '3. Build Current State'
      component: devspaces-container
      commandLine: podman build --arch=amd64 -t quay.io/michard/cities -f Containerfile
  - id: cities-podman-run
    exec:
      label: '4. Run Skaffold'
      component: devspaces-container
      commandLine: oc project dev && podman build --arch=amd64 -t quay.io/michard/cities -f Containerfile_skaffold && skaffold dev --check-cluster-node-platforms=false
  - id: podman-run
    exec:
      label: '5. Podman Remove Cities Container'
      component: devspaces-container
      commandLine: echo hello world
  - id: post-start-cmd
    exec:
      label: '6. Post Start Commands'
      component: devspaces-container
      commandLine: git config --global pull.rebase true
events:
  postStart:
    - post-start-cmd