schemaVersion: "2.2.0"
metadata:
  name: cities-demo
  namespace: smichard-devspaces
  attributes:
    metadata-name-field: generateName
    metadata-name-original-value: cities_demo
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
  controller.devfile.io/devworkspace-config:
    name: devworkspace-config
    namespace: openshift-operators
  controller.devfile.io/scc: container-build
  controller.devfile.io/storage-type: per-user
  dw.metadata.annotations:
    che.eclipse.org/devfile-source: |
      url:
        location: https://github.com/smichard/cities_demo
      factory:
        params: url=https://github.com/smichard/cities_demo
projects:
  - name: cities-demo
    git:
      remotes:
        origin: https://github.com/smichard/cities_demo.git
components:
  - name: universal-developer-image
    container:
      image: registry.redhat.io/devspaces/udi-rhel8@sha256:de81824e6ccf82a286a28566432d4f43928a989c570578c4b4df9484ef136cca
      sourceMapping: /projects
      env:
        - name: CHE_DASHBOARD_URL
          value: https://devspaces.apps.ocp.michard.cc
        - name: CHE_PLUGIN_REGISTRY_URL
          value: https://devspaces.apps.ocp.michard.cc/plugin-registry/v3
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: http://plugin-registry.openshift-operators.svc:8080/v3
        - name: CLUSTER_CONSOLE_URL
          value: https://console-openshift-console.apps.ocp.michard.cc
        - name: CLUSTER_CONSOLE_TITLE
          value: OpenShift console
        - name: OPENVSX_REGISTRY_URL
          value: ''
        #- name: ENV KUBEDOCK_ENABLED
        #  value: true
  - name: tooling-container
    container:
      #image: quay.io/michard/developer_image:dev
      image: quay.io/mloriedo/universal-developer-image:kubedock
      memoryRequest: 2Gi
      memoryLimit: 8Gi
      cpuRequest: 1000m
      cpuLimit: 4000m
      env:
        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2475'
        - name: CONTAINER_HOST
          value: 'tcp://127.0.0.1:2475'
        - name: TESTCONTAINERS_RYUK_DISABLED
          value: 'true'
        - name: TESTCONTAINERS_CHECKS_DISABLE
          value: 'true'
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475      
commands:
  - id: start-kubedock
    exec:
      label: '1. Start kubedock'
      component: tooling-container
      commandLine: kubedock server --port-forward
  - id: pull
    exec:
      label: '2. Pull Base Image'
      component: universal-developer-image
      commandLine: podman pull registry.access.redhat.com/ubi8/nginx-122
  - id: build
    exec:
      label: '3. Build Current State'
      component: universal-developer-image
      commandLine: podman build -t current-state -f Containerfile
  - id: cities-podman-run
    exec:
      label: '4. Podman Run Cities Container'
      component: universal-developer-image
      commandLine: podman --remote --url "tcp://127.0.0.1:2475" run --name cities -d -p 8090:8080 quay.io/michard/cities
  - id: podman-run
    exec:
      label: '5. Podman Remove Cities Container'
      component: tooling-container
      commandLine: podman --remote --url "tcp://127.0.0.1:2475" rm cities
