apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cities-demo-dev
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: quay.io/michard/cities_skaffold
      custom:
        buildCommand: ./custom_build.sh
        dependencies:
          paths:
          - .
      sync:
        manual:
        - src: 'website/*.html'
          dest: /usr/share/nginx/html/
manifests:
  rawYaml:
    - k8s/skaffold/deployment.yml
    - k8s/skaffold/route.yml
    - k8s/skaffold/service.yml
