apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cities-demo-gitops-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/smichard/cities_demo'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
