kind: Deployment
apiVersion: apps/v1
metadata:
  name: cities-demo-dev
  namespace: dev
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/smichard/cities_demo'
  generation: 72
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cities-demo-dev
  template:
    metadata:
      labels:
        app: cities-demo-dev
        deployment: cities-demo-dev
    spec:
      containers:
        - name: cities-demo-dev
          image: quay.io/michard/cities:skaffold
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600