kind: Deployment
apiVersion: apps/v1
metadata:
  name: cities-demo-gitops
  namespace: demo
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/smichard/cities_demo'
    ci.buildid: '0.5.22'
spec:
  replicas: 9
  selector:
    matchLabels:
      app: cities-demo-gitops
  template:
    metadata:
      labels:
        app: cities-demo-gitops
        deployment: cities-demo-gitops
    spec:
      containers:
        - name: cities-demo-gitops
          image: quay.io/michard/cities_tekton:0.5.54
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
