kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cities-demo
  namespace: cities-demo
  uid: a04acc88-8a0b-4dc0-b9cd-17a4436e05de
  resourceVersion: '33039'
  creationTimestamp: '2023-10-02T09:34:53Z'
  labels:
    app: cities-demo
    app.kubernetes.io/component: cities-demo
    app.kubernetes.io/instance: cities-demo
    app.kubernetes.io/name: cities-demo
    app.kubernetes.io/part-of: cities-demo-app
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-version: 1.20-ubi7
  annotations:
    openshift.io/host.generated: 'true'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2023-10-02T09:34:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:tls':
            .: {}
            'f:insecureEdgeTerminationPolicy': {}
            'f:termination': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2023-10-02T09:34:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
      subresource: status
spec:
  host: cities-demo-cities-demo.apps.ocp.michard.cc
  to:
    kind: Service
    name: cities-demo
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: cities-demo-cities-demo.apps.ocp.michard.cc
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2023-10-02T09:34:53Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.ocp.michard.cc