apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cities-demo-test-short
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: "Url of the git repo for the code of deployment"
    default: https://github.com/smichard/cities_demo
  - name: git-revision
    type: string
    description: "Revision to be used from repo of the code for deployment"
    default: main
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: get-git-tag
    taskRef:
      name: get-git-tag
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: generate-changelog
    taskRef:
      name: generate-changelog
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: repo-url
      value: $(params.git-url)
    - name: changelog-file-name
      value: "CHANGELOG.md"      
    runAfter:
    - fetch-repository
