apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cities-demo-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: cities-demo
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
        storageClassName: managed-nfs-storage
        volumeMode: Filesystem
  - name: registry-credentials
    secret:
      secretName: quay-creds
  - name: github-credentials
    secret:
      secretName: github-creds
  params:
  - name: git-url
    value: "https://github.com/smichard/cities_demo"
  - name: git-revision
    value: "main"
  - name: git-user-name
    value: "Stephan Michard"
  - name: git-user-mail
    value: "stephan.michard@gmail.com"
  - name: git-ssh-url
    value: git@github.com:smichard/cities_demo.git
  - name: image
    value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/cities-demo"
  - name: target-image
    value: "quay.io/michard/cities:tekton"
  - name: message
    value: "Cities Demo: new image build and pushed to internal and external registry. Build Tag:"
  - name: notification-secret
    value: "matrix-secret"