apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cities-demo
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: "Url of the git repo for the code of deployment"
    default: https://github.com/smichard/cities_demo
  - name: git-revision
    type: string
    description: "Revision to be used from repo of the code for deployment"
    default: main
  - name: image
    type: string
    description: "Image to be build from the code and push to internal registry"
    default: image-registry.openshift-image-registry.svc:5000/<namespace>/cities-pipeline-demo
  tasks:
  - name: fetch-repository
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: namespace
        value: openshift-pipelines
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: URL
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image-internal
    retries: 3
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: buildah
      - name: namespace
        value: openshift-pipelines
    params:
    - name: IMAGE
      value: $(params.image)
    - name: DOCKERFILE
      value: "./Containerfile"
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository