name: generate-changelog

on:
  create:
    tags:
      - '*'

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Changelog
        uses: AlexxNB/chalogen@master
        with:
          title: Changelog
          list: feat,fix,ci,perf,docs,other 
      - name: Commit Changelog to repository
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: 'docs(Changelog): Update Changelog'
          file_pattern: CHANGELOG.md