name: trigger-argo-cd
on:
  push:
    paths:
      - 'k8s/**'
jobs:
  argo_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ArgoCD Webhook      
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "ref": "${{ github.ref }}",
            "repository": {
              "git_url": "https://github.com/${{ github.repository }}.git",
              "url": "https://github.com/${{ github.repository }}",
              "name": "${{ github.repository }}"
            },
            "pusher": {
              "name": "${{ github.actor }}"
            },
            "head_commit": {
              "id": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}",
              "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            }
          }' https://openshift-gitops-server-openshift-gitops.apps.ocp.michard.cc/api/webhook

      - name: notification
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: |
            "${{ github.repository }}": changes to configuration directory detected<br />
            **Argo CD reconciliation triggered**<br />
            commit message: **${{ github.event.head_commit.message }}** <br />
            contributor: **${{ github.actor }}** <br />
            commit sha: **${{ github.sha }}** <br />
            commit history: **[link](https://github.com/${{ github.repository }}/commits/main)** <br />
            ArgoCD: **[link](https://openshift-gitops-server-openshift-gitops.apps.ocp.michard.cc/applications/openshift-gitops/cities-demo-gitops-app?view=tree&resource=)** <br />